### ISSUE TITLE
yum install of dependencies might fail due to another process using yum

### ISSUE THREAD

**Issue by ckamps** [aws-samples/vpn-gateway-strongswan#23]
If another process on the EC2 instance has the Yum repo locked while the following yum operations are attempted, the yum client could timeout and an error could occur stating that one of the following packages could not be found.

```
        04-config-vpn-gateway-config:
          packages:
            yum:
              strongswan: []
              ntp: []
              quagga: []
              jq: []
```

For example, if your organization has an automated patching process that aggressively attempts to perform a yum update operation on even newly spun up EC2 instances.
